### ISSUE TITLE
macOS needs swig to install properly.

### ISSUE THREAD

**Issue by AlexPatrie** [biosimulators/Biosimulators_AMICI#6]
When calling `pip install biosimulators-amici` in my python3.10 conda environment, there was an error building the wheel due to the PEP517-style build. After using `brew install swig` and re-running my pypi download, it was successful. I am not sure if this is a Mac-specific issue.

**Comment by FFroehlich** [comment]
Thanks for reporting this. We are not maintaining the conda recipe, but requiring swig is expected: https://amici.readthedocs.io/en/latest/python_installation.html so I would argue this is working as expected.
