### ISSUE TITLE
Fix CI

### ISSUE THREAD

**Issue by luciansmith** [biosimulators/Biosimulators_AMICI#7]
The current CI for Amici fails in the 'build docker image' step with the following error:

```
      In file included from /tmp/pip-install-x9gsklsq/amici_0d1b10f132da4e86a60eafeef71a84e6/amici/src/solver_idas.cpp:4:
      /tmp/pip-install-x9gsklsq/amici_0d1b10f132da4e86a60eafeef71a84e6/amici/include/amici/model_dae.h: In constructor ‘amici::Model_DAE::Model_DAE(const amici::ModelDimensions&, amici::SimulationParameters, amici::SecondOrderMode, const std::vector<double>&, const std::vector<int>&, bool, int, int, int)’:
      /tmp/pip-install-x9gsklsq/amici_0d1b10f132da4e86a60eafeef71a84e6/amici/include/amici/model_dae.h:60:18: error: ‘reduce’ is not a member of ‘std’
                   std::reduce(idlist.begin(), idlist.end())
                        ^~~~~~
      /tmp/pip-install-x9gsklsq/amici_0d1b10f132da4e86a60eafeef71a84e6/amici/include/amici/model_dae.h:60:18: note: suggested alternative: ‘deque’
                   std::reduce(idlist.begin(), idlist.end())
                        ^~~~~~
                        deque
      ninja: build stopped: subcommand failed.
```

'reduce' is a feature of C++17, so the problem is probably that we need a newer C++ compiler on the Docker image.  Though I don't know how it worked in the past with this problem?  Maybe Amici's source itself was updated in the intervening year-ish since the last successful build.

**Comment by dweindl** [comment]
Hi Lucian, recent AMICI versions need a C++17-compatible compiler, that's correct. Can we easily change the base image to `3.11-slim-bookworm` without breaking anything else?

**Comment by luciansmith** [comment]
OK!  I changed the base image and mucked about a bunch, and I think the docker image is now good.  (For some reason, if I asked pip to install a particular amici version, that failed because of no sympy (even though sympy was indeed installed?) but I think it's installed anyway.

This brings us to the current problem, which is that SBML import seems to be broken:  any time any SBML file is imported, I get an error like:

```
tests/test_core_main.py:353: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
biosimulators_amici/core.py:284: in import_model_from_sbml
    sbml_importer.sbml2amici(model_name,
/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/amici/sbml_import.py:390: in sbml2amici
    ode_model = self._build_ode_model(
/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/amici/sbml_import.py:480: in _build_ode_model
    self._process_observables(observables, sigmas, noise_distributions)
/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/amici/logging.py:209: in wrapper_timer
    rval = func(*args, **kwargs)
/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/amici/sbml_import.py:14[78](https://github.com/biosimulators/Biosimulators_AMICI/actions/runs/5361138380/jobs/9726794882#step:18:79): in _process_observables
    self.add_local_symbol(obs, symbol_with_assumptions(obs))
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <amici.sbml_import.SbmlImporter object at 0x7f1d39ad7550>, key = 'AL'
value = AL

    def add_local_symbol(self, key: str, value: sp.Expr):
        """
        Add local symbols with some sanity checking for duplication which
        would indicate redefinition of internals, which SBML permits,
        but we don't.
    
        :param key:
            local symbol key
    
        :param value:
            local symbol value
        """
        if key in self._local_symbols.keys():
>           raise SBMLException(
                f"AMICI tried to add a local symbol {key} with value {value}, "
                f"but {key} was already instantiated with "
                f"{self._local_symbols[key]}. This means that there "
                f"are multiple SBML elements with SId {key}, which is "
                f"invalid SBML. This can be fixed by renaming "
                f"the elements with SId {key}."
            )
E           amici.import_utils.SBMLException: AMICI tried to add a local symbol AL with value AL, but AL was already instantiated with AL. This means that there are multiple SBML elements with SId AL, which is invalid SBML. This can be fixed by renaming the elements with SId AL.
```

**Comment by luciansmith** [comment]
https://github.com/biosimulators/Biosimulators_AMICI/actions/runs/5361138380/jobs/9726794882

**Comment by luciansmith** [comment]
(Also, I can't check this on my Windows machine, because Amici seems to be distributed on pip as a build-your-own-binary thing, which doesn't compile for me.  I don't suppose Amici could supply pip with binaries instead of source code?)

**Comment by dweindl** [comment]
> I changed the base image and mucked about a bunch, and I think the docker image is now good.
 
 Great, thanks.
 
 > I asked pip to install a particular amici version, that failed because of no sympy (even though sympy was indeed installed?) but I think it's installed anyway.

We had some issue that certain versions of amici and setuptools didn't work well and could lead to such an error. I think this was >1y ago, though.

> E           amici.import_utils.SBMLException: AMICI tried to add a local symbol AL with value AL, but AL was already instantiated with AL. This means that there are multiple SBML elements with SId AL, which is invalid SBML. This can be fixed by renaming the elements with SId AL.

I will look into that. 

> I don't suppose Amici could supply pip with binaries instead of source code?

We could ship the pre-built core library, but we'd still need the whole tool chain when importing a model.

**Comment by luciansmith** [comment]
Thanks for the fixes!  With those and other tweaks, everything finally works again.

**Comment by dweindl** [comment]
Cool, thanks!

**Comment by luciansmith** [comment]
And, as a further update, 0.18.1 of Amici is now up and running on biosimulations, replacing 0.11.25
